name: Fetch HDNEA Token at Scheduled Times

on:
  schedule:
    # 4:00 AM IST ≈ 22:30 UTC → nearest 23:00 UTC (3:30 AM IST)
    - cron: '0 24 * * *'
    # 8:00 AM IST ≈ 02:30 UTC → nearest 3:00 UTC (8:30 AM IST)
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  fetch-hdnea-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Fetch __hdnea__ token from cookies.json
        run: |
          echo "Fetching token from https://fftv.in/jpls/cookies.json"

          response=$(curl -s "https://fftv.in/jpls/cookies.json")
          echo "Response: $response"

          token=$(echo "$response" | jq -r '.[0].cookie' | sed 's/^__hdnea__=//')

          if [ -z "$token" ] || [[ "$token" == "null" ]]; then
            echo "::error ::Failed to extract __hdnea__ token"
            exit 1
          fi

          echo "__hdnea__=$token" > fetch.txt
          echo "Token saved to fetch.txt"

      - name: Run Python Script to update channels.json
        run: python append_hdnea_token.py

      - name: Commit and push updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add fetch.txt channels.json
          git diff --cached --quiet || git commit -m "Update fetch.txt and channels.json - $(date -u)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
